/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * API version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package facebookgen

type Event struct {
	// A Facebook pixel Standard Event or Custom Event name. This field is used to deduplicate events sent by both Facebook Pixel and Conversions API. event_id is also used in deduplication. For the same customer action, event from the browser event match event_name from the server event. If we find a match between events sent within 48 hours of each other, we only consider the first one. If a server and browser event arrive at approximately the same time (within 5 minutes of each other), we favor the browser event.
	EventName string `json:"event_name"`
	// A Unix timestamp in seconds indicating when the actual event occurred. The specified time may be earlier than the time you send the event to Facebook. This is to enable batch processing and server performance optimization. event_time can be up to 7 days before you send an event to Facebook. If any event_time in data is greater than 7 days in the past, we return an error for the entire request and process no events.
	EventTime int64 `json:"event_time"`
	// The browser URL where the event happened.
	EventSourceUrl string `json:"event_source_url,omitempty"`
	// A flag that indicates we should not use this event for ads delivery optimization. If set to true, we only use the event for attribution.
	OptOut bool `json:"opt_out,omitempty"`
	// This ID can be any unique string chosen by the advertiser. event_id is used to deduplicate events sent by both Facebook Pixel and Conversions API. event_name is also used in deduplication. For deduplication, the eventID from a browser event must match the event_id in the corresponding server event.
	EventId string `json:"event_id,omitempty"`
	// This field allows you to specify where your conversions occurred. Knowing where your events took place helps ensure your ads go to the right people. See docs for the allowable values. https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/server-event#action-source
	ActionSource string `json:"action_source"`
	UserData *UserData `json:"user_data"`
	CustomData *CustomData `json:"custom_data,omitempty"`
	// Processing options you would like to enable for a specific event. For more details see: https://developers.facebook.com/docs/marketing-apis/data-processing-options.
	DataProcessingOptions []string `json:"data_processing_options,omitempty"`
	// The country that you want to associate to this data processing option. If you set a country, you must also set a state. For more details see: https://developers.facebook.com/docs/marketing-apis/data-processing-options
	DataProcessingOptionsCountry int32 `json:"data_processing_options_country,omitempty"`
	// The state that you want to associate with this data processing option. For more details see: https://developers.facebook.com/docs/marketing-apis/data-processing-options.
	DataProcessingOptionsState int32 `json:"data_processing_options_state,omitempty"`
}
